language: node_js
sudo: required
services:
  - docker
node_js:
  - 'lts/carbon'
jobs:
  include:
    - stage: unit
      script:
        - yarn bootstrap
        - yarn test
    - stage: itest
      script:
        - yarn bootstrap
        - yarn itest
    # - stage: package
    #   script:
    #     - npm install
    #     - npm run compile
    #     - docker build -t tksukhu/nxplorerjs-microservice .
