language: node_js
sudo: required
services:
  - docker
node_js:
  - "lts/carbon"
jobs:
  include:
    - stage: unit
      script:
        - yarn boostrap
        - yarn test
    - stage: itest
      script:
        - yarn boostrap
        - yarn itest
    # - stage: package
    #   script:
    #     - npm install
    #     - npm run compile
    #     - docker build -t tksukhu/nxplorerjs-microservice .
